routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/debug-sentry', function () {
    throw new Exception('My first Sentry error!');
});

Route::get('/', function () {
    return redirect()->action('Admin\IndexController@index');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin'], function () {
    Route::group(['namespace' => 'Auth'], function () {
        Route::get('/login', 'AuthController@showLoginForm')
            ->name('admin.login');
        Route::post('/login', 'AuthController@login')
            ->name('admin.login.submit');
        Route::get('/logout', 'AuthController@logout')->name('logout');
    });
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('/', 'IndexController@index')->name('admin.dashboard');
        Route::get('/getinfo', 'IndexController@getinfo');//del
        Route::get('/taxonomy/{slug}', 'IndexController@taxonomy')->name('admin.taxonomy');
        Route::post('/taxonomy/{id}/edit', 'IndexController@edit')->name('admin.edit.taxonomy');

        Route::group(['prefix' => 'pages'], function () {
            Route::get('{slug}', 'PageController@show')->name('admin.page.show');
            Route::get('{id}/edit', 'PageController@edit')->name('admin.page.edit');
            Route::post('{id}/update', 'PageController@update')->name('admin.page.update');
            Route::get('{slug}/create', 'PageController@create')->name('admin.page.create');
            Route::post('{slug}/store', 'PageController@store')->name('admin.page.store');
            Route::get('{slug}/destroy', 'PageController@destroy')->name('admin.page.destroy');
            Route::post('/get', 'PageController@getForDatatable')->name('admin.pages.get');
        });
        Route::group(['prefix' => 'taxonomy'], function () {
            Route::get('{slug}', 'TaxonomyController@show')->name('admin.taxonomy.show');
            Route::post('{slug}/store', 'TaxonomyController@store')->name('admin.taxonomy.store');
            Route::get('{slug}/edit', 'TaxonomyController@edit')->name('admin.term.edit');
            Route::post('{slug}/update', 'TaxonomyController@update')->name('admin.term.update');
            Route::get('{slug}/destroy', 'TaxonomyController@destroy')->name('admin.term.destroy');
        });

        Route::get('rms', 'TaxonomyController@removes')->name('admin.term.rms');


        Route::group(['prefix' => 'theme_option'], function () {
            Route::get('{slug}', 'ThemeOptionController@index')->name('admin.to');
            Route::post('{slug}/store', 'ThemeOptionController@store')->name('admin.to.store');
            Route::get('{slug}/edit', 'ThemeOptionController@edit')->name('admin.to.edit');
            Route::post('{slug}/update', 'ThemeOptionController@update')->name('admin.to.update');
            Route::get('{slug}/destroy', 'ThemeOptionController@destroy')->name('admin.to.destroy');
        });

        Route::resource('users', 'UserController', ['as' => 'admin']);
        Route::post('users/get', 'UserController@getDataTable')->name('admin.users.get');

    });

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $table = 'users';
    protected $fillable = ['login', 'email', 'password', 'status'];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Repositories\MetaRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\DataTables;



class UserController extends Controller
{
    public $repository, $meta_repository;
    public function __construct(UserRepository $repository, MetaRepository $metaRepository)
    {
        $this->repository = $repository;
        $this->meta_repository = $metaRepository;
    }



// create a log channel
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->repository->setVariable();
        $model = $this->repository->getModel();

        $this->meta_repository->setVar('usermeta', null, 'user');
        $usermeta = $this->meta_repository->show();
        $thumbnail = collect($usermeta)->where('name', '=', 'thumbnail')->collapse();
        $usermeta = collect($usermeta)->reject(function($item){ return $item['name'] == "thumbnail";});

        return view('admin.users.create', compact('model', 'thumbnail', 'usermeta'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->repository->setVariable(null, $request);
        $this->repository->save();

        $this->meta_repository->setVar('usermeta', $this->repository->model->id, 'user', array_merge($request->usermeta, $request->postmeta));
        $this->meta_repository->store();

        return redirect()->route('admin.users.edit', $this->repository->model->id)->with('success', 'Добавлен');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->repository->setVariable($id);
        $model = $this->repository->getModel();

        $this->meta_repository->setVar('usermeta', $id, 'user');
        $usermeta = $this->meta_repository->show();
        $thumbnail = collect($usermeta)->where('name', '=', 'thumbnail')->collapse();
        $usermeta = collect($usermeta)->reject(function($item){ return $item['name'] == "thumbnail";});

        return view('admin.users.edit', compact('model', 'usermeta', 'thumbnail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->repository->setVariable($id, $request);
        $status = $this->switch($request->btnQuery);

        $this->meta_repository->setVar('usermeta', $id, 'user', array_merge($request->usermeta, $request->postmeta));
        $this->meta_repository->store();
        //dd($request->usermeta, $this->meta_repository->show());

        return back()->with('success', $status);
    }

    public function switch($status)
    {
        switch($status){
            case 'r':
                $this->repository->unlock();
                return 'Пользователь разблокирован';
                break;
            case 's':
                $this->repository->save();
                return 'Изменения сохранены';
                break;
            case 'z':
                $this->repository->lock();
                return 'Пользователь заблокирован';
                break;
            default:
                return 'Произошла ошибка. Повторите попытку позже';
        }
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repository->setVariable($id);
        $this->repository->delete($id);

        return redirect()->route('admin.users.index')->with("Удален");
    }



    /**
     * @param \Illuminate\Http\Request $request
     *
     * @return mixed
     * @throws \Exception
     */
    public function getDataTable(Request $request)
    {
        return Datatables::of($this->repository->getForDataTable($request))
            ->addColumn('actions', function ($post) use($request){
                return view('admin.users.tableButtons', ['post' => $post])->render();
            })
            ->addColumn('id', function ($post) use($request){
                return str_pad($post->id, 4, 0, STR_PAD_LEFT);
            })
            ->addColumn('status', function ($post) use($request){
                $icon = $post->status?"icon-check":"icon-close";
                $color = $post->status?"green":"red";
                return "<i style='color:$color' class='$icon'>";
            })

            ->rawColumns(['actions', 'status'])
            ->make(true);
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('css-links')
<link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2.css"/>
<!-- END PAGE LEVEL SCRIPTS -->
@stop
@section('content')
    <!-- BEGIN PAGE HEADER-->
{{--        @include('admin.pages.includes.breadcrumbs', ['label' => $label, 'typehead' => 'add-block'])--}}
    <!-- END PAGE HEADER-->

    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            {!! Form::model($model, [
                'method' => 'POST',
                'route' => ['admin.users.update', $model->id]
            ]) !!}
{{--            <form action="{{ route('admin.users.store') }}" method="post" class="form-horizontal">--}}
                {{ csrf_field() }}
                @include('admin.users.includes.form')
            {{--</form>--}}
        {!! Form::close() !!}
            <!-- END VALIDATION STATES-->
        </div>
    </div>
@stop

@section('js-script')
    <script type="text/javascript" src="/assets/plugins/ckeditor/ckeditor.js"></script>

@stop

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('css-links')
<link rel="stylesheet" type="text/css" href="/assets/plugins/select2/select2.css"/>
<!-- END PAGE LEVEL SCRIPTS -->
@stop
@section('content')
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN VALIDATION STATES-->
            {!! Form::model($model, [
                'method' => 'PATCH',
                'route' => ['admin.users.update', $model->id]
            ]) !!}
{{--            <form action="{{ route('admin.users.update', $model->id) }}" method="PATCH" class="form-horizontal">--}}
                {{ csrf_field() }}
                @include('admin.users.includes.form')
            {{--</form>--}}
            {!! Form::close() !!}
            <!-- END VALIDATION STATES-->
        </div>
    </div>
@stop

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- BEGIN PAGE HEADER-->
{{--    @include('admin.pages.includes.breadcrumbs', ['labels' => $label, 'route' => $route, 'typehead' => 'sub-title'])--}}
    <!-- END PAGE HEADER-->

    <!-- BEGIN PAGE CONTENT-->
    <div class="row">
        <div class="col-md-12">
            <div class="portlet">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-edit"></i>Список пользователей
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse">
                        </a>
                        <a href="javascript:;" class="reload">
                        </a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="btn-group">
                        <a href="{{ route('admin.users.create') }}" id="sample_editable_1_new"
                           class="btn btn-success">
                            Добавить пользователя <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    <table class="table table-bordered" id="myTable">
                        <thead>
                        <tr>
                            <th>id</th>
                            <th>login</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>created_at</th>
                            <th>actions</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>id</th>
                            <th>login</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>created_at</th>
                            <th>actions</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop

@section('js-script')
    <script>
    $(function () {
        $(document).ready(function() {
            $('#myTable').DataTable( {
                processing: true,
                serverSide: true,
                ajax: {
                    url:  '{{ route("admin.users.get") }}',
                    type: 'post',
                    dataSrc: "data",
                    data: { trashed: false },
                    // error: function (xhr, err) {
                    //     if (err === 'parsererror')
                    //         location.reload();
                    // }
                },
                columns: [
                    { "data": 'id' },
                    { "data": 'login' },
                    { "data": 'email' },
                    { "data": 'status' },
                    { "data": 'created_at' },
                    { "data": 'actions' },
                ],
                "language": {
                    "sProcessing": "Подождите...",
                    "sLengthMenu": "Показать _MENU_ записей",
                    "sZeroRecords": "Записи отсутствуют.",
                    "sInfo": "Записи с _START_ до _END_ из _TOTAL_ записей",
                    "sInfoEmpty": "Записи с 0 до 0 из 0 записей",
                    "sInfoFiltered": "(отфильтровано из _MAX_ записей)",
                    "sInfoPostFix": "",
                    "sSearch": "Поиск:",
                    "sUrl": "",
                    "oPaginate": {
                        "sFirst": "Первая",
                        "sPrevious": "Предыдущая",
                        "sNext": "Следующая",
                        "sLast": "Последняя"
                    },
                    "oAria": {
                        "sSortAscending": ": активировать для сортировки столбца по возрастанию",
                        "sSortDescending": ": активировать для сортировки столбцов по убыванию"
                    }
                }
            } );
        } );


        $("html").on("click", ".btn-xs.btn-danger", function(event) {
            if (confirm("Вы уверены что хотите удалить статью?")) {
                var tr = $(this).closest("tr");
                var id = $(this).attr("data-id");
                var token = $("meta[name=csrf-token]").text();
                $.post(`/admin/articles/${id}`, {"_method" : "DELETE", "_token" : token}, function(data) {
                    var result = $("<div/>").html($(data));
                    tr.remove();
                    $("section.content > .box.box-success").before(result.find(".alert.alert-success"));
                });
            }
            event.preventDefault();
        });
    });
</script>
@stop

resources/views/admin/users/tableButtons.blade.php
<a class="edit" href="{{ route('admin.users.edit', $post->id) }}"
   title="Редактирование">
    <i class="icon-pencil" style="font-size: 14pt;margin:0 5px;"></i>
</a>
<a class="delete" href="{{ route('admin.users.destroy', $post->id) }}"
   title="Удаление">
    <i class="icon-trash" style="font-size: 14pt;margin:0 5px;"></i>
</a>